#!/usr/bin/env node
// THE MODULE MAP IS GENERATED FROM THE SOURCE, NOT WRITTEN BESIDE IT.
//
// docs/ARCHITECTURE.md is good and it went stale inside a day: it still said
// "Aero Red" the morning after that look was renamed, and nothing could see it.
// A reference nobody can trust is worse than none, because it is consulted.
//
// So the map is not maintained. It is DERIVED: every file under src/ opens with
// a comment saying what it is — that convention already held across all 69 of
// them when this was written — and this regenerates the map from those comments
// and refuses the commit when the map in the tree and the source disagree.
//
// WHAT THAT BUYS, and it is the whole point: a new module cannot be added
// without appearing here, a deleted one cannot linger, and a purpose that
// changes in the code changes in the map. The description lives next to the
// code, where the author is already writing it, rather than in a document
// somebody has to remember to open.
//
//   node tools/architecture-check.mjs            check, exit 1 on drift
//   node tools/architecture-check.mjs --write    regenerate the region
//
// Runs on every commit through .branch-guard's `also=`. Text only, no browser,
// milliseconds.
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const DOC = join(ROOT, "docs/ARCHITECTURE.md");
const START = "<!-- MODULE MAP: generated by tools/architecture-check.mjs — do not hand-edit -->";
const END = "<!-- END MODULE MAP -->";
const write = process.argv.includes("--write");

function walk(dir) {
  const out = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (e.endsWith(".ts")) out.push(p);
  }
  return out;
}

/** THE COMMENT BLOCK AT THE VERY TOP OF A FILE, before any statement — not the
 *  first comment anywhere in it. That distinction is load-bearing: the first
 *  version of this took the first comment it found and read main.ts's purpose
 *  off a note attached to an import, which is how a generator produces
 *  confident nonsense. A file whose first line is code has no purpose stated
 *  and is a FAILURE, not a blank row. */
function purpose(file) {
  const lines = readFileSync(file, "utf8").split("\n");
  const said = [];
  let i = 0;
  while (i < lines.length && lines[i].trim() === "") i++;
  if (lines[i]?.trim().startsWith("/*")) {
    for (; i < lines.length; i++) {
      const t = lines[i].replace(/^\s*\/\*\*?/, "").replace(/\*\/\s*$/, "").replace(/^\s*\*\s?/, "").trim();
      if (t) said.push(t);
      if (lines[i].includes("*/")) { i++; break; }
    }
  } else {
    for (; i < lines.length && lines[i].trim().startsWith("//"); i++) {
      const t = lines[i].replace(/^\s*\/\/\s?/, "").trim();
      said.push(t);
    }
  }
  const text = said.join(" ").replace(/\s+/g, " ").trim();
  return text;
}

/** One sentence, or the first 200 characters if the opening comment does not
 *  punctuate. Enough to answer "where does X happen" from the map alone. */
function oneLine(text) {
  const m = text.match(/^(.{20,200}?[.!?])(\s|$)/);
  return (m ? m[1] : text.slice(0, 200)).trim();
}

const files = walk(join(ROOT, "src")).sort();
const rows = [];
const missing = [];
for (const f of files) {
  const rel = relative(ROOT, f);
  const p = purpose(f);
  if (p.length < 20) { missing.push(rel); continue; }
  const n = readFileSync(f, "utf8").split("\n").length;
  rows.push(`- **\`${rel}\`** (${n} lines) — ${oneLine(p)}`);
}

const generated = [
  START,
  "",
  `${files.length} modules. Each line is that file's own opening comment, so this`,
  "cannot describe something the code does not say about itself.",
  "",
  ...rows,
  "",
  END,
].join("\n");

let doc = readFileSync(DOC, "utf8");
const a = doc.indexOf(START), b = doc.indexOf(END);

if (missing.length) {
  console.log(`FAIL  ${missing.length} module(s) do not open with a comment saying what they are:`);
  for (const m of missing) console.log(`        ${m}`);
  console.log("\n  A module map generated from the source can only be as good as the source.");
  process.exit(1);
}

if (a === -1 || b === -1) {
  if (!write) {
    console.log("FAIL  docs/ARCHITECTURE.md has no MODULE MAP region.");
    console.log("      Run: node tools/architecture-check.mjs --write");
    process.exit(1);
  }
  doc = doc.trimEnd() + "\n\n## Module map\n\n" + generated + "\n";
  writeFileSync(DOC, doc);
  console.log(`  wrote a new MODULE MAP region, ${rows.length} modules`);
  process.exit(0);
}

const current = doc.slice(a, b + END.length);
if (current === generated) {
  console.log(`  ok    the module map matches the source (${rows.length} modules)`);
  process.exit(0);
}
if (write) {
  writeFileSync(DOC, doc.slice(0, a) + generated + doc.slice(b + END.length));
  console.log(`  wrote the MODULE MAP region, ${rows.length} modules`);
  process.exit(0);
}
console.log("FAIL  the module map and the source disagree.");
const was = current.split("\n").filter(l => l.startsWith("- **"));
const now = generated.split("\n").filter(l => l.startsWith("- **"));
const name = (l) => (l.match(/`([^`]+)`/) || [, l])[1];
for (const l of now) if (!was.includes(l)) console.log(`        + ${name(l)}`);
for (const l of was) if (!now.includes(l)) console.log(`        - ${name(l)}`);
console.log("\n  Run: node tools/architecture-check.mjs --write");
process.exit(1);
