// DNG Camera Profile (.dcp) export for Lightroom / Camera Raw.
//
// Encodes the creative look (channel swap + hue + saturation, plus a tone curve
// for contrast) as a ProfileHueSatMap, and embeds the camera's ColorMatrix.
// White balance stays the user's per-shot adjustment (it is raw-domain).
//
// IMPORTANT: the .cube path is verified numerically here; a .dcp's *colour*
// can only be confirmed inside Lightroom/ACR (not available in this build env),
// so this is a v1 to validate in Lightroom. Structure is validated against a
// TIFF/DNG reader.

import type { EditParams } from "./pipeline";
import { Tiff } from "./raw/tiff";

// Nikon Z 50 ColorMatrix1 (D65), from the public Adobe coefficients, /10000.
const Z50_COLOR_MATRIX = [
  1.1853, -0.4189, -0.1024, -0.4292, 1.2041, 0.2569, -0.1336, 0.2599, 0.5824,
];

const HUE_DIVS = 36;
const SAT_DIVS = 8;
const VAL_DIVS = 1;

const TYPE = { ASCII: 2, SHORT: 3, LONG: 4, SRATIONAL: 10, FLOAT: 11 } as const;

interface Entry {
  tag: number;
  type: number;
  count: number;
  bytes: Uint8Array; // raw value bytes (little-endian)
}

export function generateDcp(params: EditParams, sourceBytes: Uint8Array | undefined, name = "IPS IR Look"): ArrayBuffer {
  const colorMatrix = readColorMatrix(sourceBytes) ?? Z50_COLOR_MATRIX;
  const hsm = buildHueSatMap(params);
  const tone = buildToneCurve(params.contrast);

  const entries: Entry[] = [
    asciiEntry(50708, "NIKON Z 50"), // UniqueCameraModel
    srationalEntry(50721, colorMatrix), // ColorMatrix1
    shortEntry(50778, [21]), // CalibrationIlluminant1 = D65
    asciiEntry(50936, name), // ProfileName
    longEntry(50937, [HUE_DIVS, SAT_DIVS, VAL_DIVS]), // ProfileHueSatMapDims
    floatEntry(50938, hsm), // ProfileHueSatMapData1
    floatEntry(50940, tone), // ProfileToneCurve
    longEntry(50941, [1]), // ProfileEmbedPolicy = embed allowed
    asciiEntry(50942, "Generated by Infrared Photography Studio"), // ProfileCopyright
  ];
  entries.sort((a, b) => a.tag - b.tag);

  return assembleTiff(entries);
}

// --- look table ---

/** Creative transform in LINEAR space (no gamma, no WB) — for HSV deltas. */
function creativeLinear(r: number, g: number, b: number, p: EditParams): [number, number, number] {
  if (p.swapRB) {
    const t = r;
    r = b;
    b = t;
  }
  const a = (p.hue * Math.PI) / 180;
  const cos = Math.cos(a), sin = Math.sin(a);
  const c00 = 0.299 + 0.701 * cos + 0.168 * sin, c01 = 0.587 - 0.587 * cos + 0.33 * sin, c02 = 0.114 - 0.114 * cos - 0.497 * sin;
  const c10 = 0.299 - 0.299 * cos - 0.328 * sin, c11 = 0.587 + 0.413 * cos + 0.035 * sin, c12 = 0.114 - 0.114 * cos + 0.292 * sin;
  const c20 = 0.299 - 0.3 * cos + 1.25 * sin, c21 = 0.587 - 0.588 * cos - 1.05 * sin, c22 = 0.114 + 0.886 * cos - 0.203 * sin;
  let nr = c00 * r + c10 * g + c20 * b;
  let ng = c01 * r + c11 * g + c21 * b;
  let nb = c02 * r + c12 * g + c22 * b;
  const luma = nr * 0.2126 + ng * 0.7152 + nb * 0.0722;
  nr = luma + (nr - luma) * p.sat;
  ng = luma + (ng - luma) * p.sat;
  nb = luma + (nb - luma) * p.sat;
  return [nr, ng, nb];
}

/** ProfileHueSatMapData1: per (hue, sat) -> [hueShiftDeg, satScale, valScale]. */
function buildHueSatMap(p: EditParams): number[] {
  const data: number[] = [];
  for (let h = 0; h < HUE_DIVS; h++) {
    for (let s = 0; s < SAT_DIVS; s++) {
      const hue = (h * 360) / HUE_DIVS;
      const sat = SAT_DIVS > 1 ? s / (SAT_DIVS - 1) : 0;
      const val = 0.5;
      const [r, g, b] = hsv2rgb(hue, sat, val);
      const [nr, ng, nb] = creativeLinear(r, g, b, p);
      const [oh, os, ov] = rgb2hsv(nr, ng, nb);
      let dh = oh - hue;
      while (dh > 180) dh -= 360;
      while (dh < -180) dh += 360;
      data.push(sat < 1e-4 ? 0 : dh, sat < 1e-4 ? 1 : clampScale(os / sat), clampScale(ov / val));
    }
  }
  return data;
}

/** ProfileToneCurve: a few (x,y) points approximating RGB contrast about 0.5. */
function buildToneCurve(contrast: number): number[] {
  const pts: number[] = [];
  for (let i = 0; i <= 8; i++) {
    const x = i / 8;
    const y = Math.min(1, Math.max(0, (x - 0.5) * contrast + 0.5));
    pts.push(x, y);
  }
  return pts;
}

function clampScale(v: number): number {
  return Math.min(8, Math.max(0.01, v));
}

// --- HSV helpers ---

function hsv2rgb(h: number, s: number, v: number): [number, number, number] {
  const c = v * s;
  const hh = h / 60;
  const x = c * (1 - Math.abs((hh % 2) - 1));
  let r = 0, g = 0, b = 0;
  if (hh < 1) [r, g, b] = [c, x, 0];
  else if (hh < 2) [r, g, b] = [x, c, 0];
  else if (hh < 3) [r, g, b] = [0, c, x];
  else if (hh < 4) [r, g, b] = [0, x, c];
  else if (hh < 5) [r, g, b] = [x, 0, c];
  else [r, g, b] = [c, 0, x];
  const m = v - c;
  return [r + m, g + m, b + m];
}

function rgb2hsv(r: number, g: number, b: number): [number, number, number] {
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  const d = max - min;
  let h = 0;
  if (d > 1e-9) {
    if (max === r) h = ((g - b) / d) % 6;
    else if (max === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    h *= 60;
    if (h < 0) h += 360;
  }
  return [h, max < 1e-9 ? 0 : d / max, max];
}

// --- TIFF assembly ---

function assembleTiff(entries: Entry[]): ArrayBuffer {
  const n = entries.length;
  const ifdStart = 8;
  const ifdSize = 2 + n * 12 + 4;
  let extOffset = ifdStart + ifdSize;
  const externals: { at: number; bytes: Uint8Array }[] = [];
  for (const e of entries) {
    if (e.bytes.length > 4) {
      if (extOffset & 1) extOffset++; // word align
      externals.push({ at: extOffset, bytes: e.bytes });
      (e as Entry & { _off?: number })._off = extOffset;
      extOffset += e.bytes.length;
    }
  }
  const buf = new ArrayBuffer(extOffset);
  const dv = new DataView(buf);
  const u8 = new Uint8Array(buf);
  dv.setUint16(0, 0x4949, true); // little-endian
  dv.setUint16(2, 42, true);
  dv.setUint32(4, ifdStart, true);
  dv.setUint16(ifdStart, n, true);

  let p = ifdStart + 2;
  for (const e of entries) {
    dv.setUint16(p, e.tag, true);
    dv.setUint16(p + 2, e.type, true);
    dv.setUint32(p + 4, e.count, true);
    if (e.bytes.length <= 4) {
      u8.set(e.bytes, p + 8);
    } else {
      dv.setUint32(p + 8, (e as Entry & { _off: number })._off, true);
    }
    p += 12;
  }
  dv.setUint32(p, 0, true); // next IFD
  for (const ext of externals) u8.set(ext.bytes, ext.at);
  return buf;
}

function asciiEntry(tag: number, s: string): Entry {
  const bytes = new Uint8Array(s.length + 1);
  for (let i = 0; i < s.length; i++) bytes[i] = s.charCodeAt(i);
  return { tag, type: TYPE.ASCII, count: bytes.length, bytes };
}

function shortEntry(tag: number, vals: number[]): Entry {
  const bytes = new Uint8Array(vals.length * 2);
  const dv = new DataView(bytes.buffer);
  vals.forEach((v, i) => dv.setUint16(i * 2, v, true));
  return { tag, type: TYPE.SHORT, count: vals.length, bytes };
}

function longEntry(tag: number, vals: number[]): Entry {
  const bytes = new Uint8Array(vals.length * 4);
  const dv = new DataView(bytes.buffer);
  vals.forEach((v, i) => dv.setUint32(i * 4, v, true));
  return { tag, type: TYPE.LONG, count: vals.length, bytes };
}

function floatEntry(tag: number, vals: number[]): Entry {
  const bytes = new Uint8Array(vals.length * 4);
  const dv = new DataView(bytes.buffer);
  vals.forEach((v, i) => dv.setFloat32(i * 4, v, true));
  return { tag, type: TYPE.FLOAT, count: vals.length, bytes };
}

function srationalEntry(tag: number, vals: number[]): Entry {
  const bytes = new Uint8Array(vals.length * 8);
  const dv = new DataView(bytes.buffer);
  vals.forEach((v, i) => {
    dv.setInt32(i * 8, Math.round(v * 10000), true);
    dv.setInt32(i * 8 + 4, 10000, true);
  });
  return { tag, type: TYPE.SRATIONAL, count: vals.length, bytes };
}

function readColorMatrix(sourceBytes: Uint8Array | undefined): number[] | undefined {
  if (!sourceBytes) return undefined;
  try {
    if (sourceBytes[0] !== 0x49 && sourceBytes[0] !== 0x4d) return undefined;
    for (const ifd of new Tiff(sourceBytes).allIfds()) {
      const cm = ifd.num(50721);
      if (cm.length === 9) return cm;
    }
  } catch {
    /* fall through to default */
  }
  return undefined;
}
